package io.legado.app.ui.theme.colorScheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import io.legado.app.ui.theme.BaseColorScheme

internal object CarlottaColorScheme : BaseColorScheme() {

    override val lightScheme = lightColorScheme(
        primary = Color(0xFF8B4A62),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFFD9E3),
        onPrimaryContainer = Color(0xFF6F334A),
        secondary = Color(0xFF74565F),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFFFD9E3),
        onSecondaryContainer = Color(0xFF5A3F48),
        tertiary = Color(0xFF7D5635),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFFFDCC2),
        onTertiaryContainer = Color(0xFF623F20),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF93000A),
        background = Color(0xFFFFF8F8),
        onBackground = Color(0xFF22191C),
        surface = Color(0xFFFFF8F8),
        onSurface = Color(0xFF22191C),
        surfaceVariant = Color(0xFFF2DDE2),
        onSurfaceVariant = Color(0xFF514347),
        outline = Color(0xFF837377),
        outlineVariant = Color(0xFFD5C2C6),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFF372E30),
        inverseOnSurface = Color(0xFFFDEDF0),
        inversePrimary = Color(0xFFFFB0CA),
        primaryFixed = Color(0xFFFFD9E3),
        onPrimaryFixed = Color(0xFF39071E),
        primaryFixedDim = Color(0xFFFFB0CA),
        onPrimaryFixedVariant = Color(0xFF6F334A),
        secondaryFixed = Color(0xFFFFD9E3),
        onSecondaryFixed = Color(0xFF2B151D),
        secondaryFixedDim = Color(0xFFE2BDC7),
        onSecondaryFixedVariant = Color(0xFF5A3F48),
        tertiaryFixed = Color(0xFFFFDCC2),
        onTertiaryFixed = Color(0xFF2E1500),
        tertiaryFixedDim = Color(0xFFEFBC94),
        onTertiaryFixedVariant = Color(0xFF623F20),
        surfaceDim = Color(0xFFE6D6D9),
        surfaceBright = Color(0xFFFFF8F8),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFFFF0F2),
        surfaceContainer = Color(0xFFFAEAED),
        surfaceContainerHigh = Color(0xFFF4E4E7),
        surfaceContainerHighest = Color(0xFFEFDFE2),
    )

    override val darkScheme = darkColorScheme(
        primary = Color(0xFFFFB0CA),
        onPrimary = Color(0xFF541D33),
        primaryContainer = Color(0xFF6F334A),
        onPrimaryContainer = Color(0xFFFFD9E3),
        secondary = Color(0xFFE2BDC7),
        onSecondary = Color(0xFF422931),
        secondaryContainer = Color(0xFF5A3F48),
        onSecondaryContainer = Color(0xFFFFD9E3),
        tertiary = Color(0xFFEFBC94),
        onTertiary = Color(0xFF48290C),
        tertiaryContainer = Color(0xFF623F20),
        onTertiaryContainer = Color(0xFFFFDCC2),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        background = Color(0xFF191114),
        onBackground = Color(0xFFEFDFE2),
        surface = Color(0xFF191114),
        onSurface = Color(0xFFEFDFE2),
        surfaceVariant = Color(0xFF514347),
        onSurfaceVariant = Color(0xFFD5C2C6),
        outline = Color(0xFF9E8C90),
        outlineVariant = Color(0xFF514347),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFFEFDFE2),
        inverseOnSurface = Color(0xFF372E30),
        inversePrimary = Color(0xFF8B4A62),
        primaryFixed = Color(0xFFFFD9E3),
        onPrimaryFixed = Color(0xFF39071E),
        primaryFixedDim = Color(0xFFFFB0CA),
        onPrimaryFixedVariant = Color(0xFF6F334A),
        secondaryFixed = Color(0xFFFFD9E3),
        onSecondaryFixed = Color(0xFF2B151D),
        secondaryFixedDim = Color(0xFFE2BDC7),
        onSecondaryFixedVariant = Color(0xFF5A3F48),
        tertiaryFixed = Color(0xFFFFDCC2),
        onTertiaryFixed = Color(0xFF2E1500),
        tertiaryFixedDim = Color(0xFFEFBC94),
        onTertiaryFixedVariant = Color(0xFF623F20),
        surfaceDim = Color(0xFF191114),
        surfaceBright = Color(0xFF403739),
        surfaceContainerLowest = Color(0xFF140C0E),
        surfaceContainerLow = Color(0xFF22191C),
        surfaceContainer = Color(0xFF261D20),
        surfaceContainerHigh = Color(0xFF31282A),
        surfaceContainerHighest = Color(0xFF3C3235),
    )
}