package io.legado.app.ui.theme.colorScheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import io.legado.app.ui.theme.BaseColorScheme

internal object ElinkColorScheme : BaseColorScheme() {

    override val lightScheme = lightColorScheme(
        primary = Color(0xFF000000),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFF000000),
        onPrimaryContainer = Color(0xFFFFFFFF),
        secondary = Color(0xFF000000),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFF808080),
        onSecondaryContainer = Color(0xFFFFFFFF),
        tertiary = Color(0xFF000000),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFF000000),
        onTertiaryContainer = Color(0xFFFFFFFF),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF93000A),
        background = Color(0xFFFFFFFF),
        onBackground = Color(0xFF000000),
        surface = Color(0xFFFFFFFF),
        onSurface = Color(0xFF000000),
        surfaceVariant = Color(0xFFFFFFFF),
        onSurfaceVariant = Color(0xFF000000),
        outline = Color(0xFF000000),
        outlineVariant = Color(0xFF000000),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFF313030),
        inverseOnSurface = Color(0xFFFFFFFF),
        inversePrimary = Color(0xFFFFFFFF),
        primaryFixed = Color(0xFFFFFFFF),
        onPrimaryFixed = Color(0xFF1A1C1C),
        primaryFixedDim = Color(0xFFC6C6C7),
        onPrimaryFixedVariant = Color(0xFF454747),
        secondaryFixed = Color(0xFFE2E2E2),
        onSecondaryFixed = Color(0xFF1B1B1B),
        secondaryFixedDim = Color(0xFFC6C6C6),
        onSecondaryFixedVariant = Color(0xFF474747),
        tertiaryFixed = Color(0xFFFFFFFF),
        onTertiaryFixed = Color(0xFF1B1B1B),
        tertiaryFixedDim = Color(0xFFC6C6C6),
        onTertiaryFixedVariant = Color(0xFF474747),
        surfaceDim = Color(0xFFFFFFFF),
        surfaceBright = Color(0xFFFFFFFF),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFFFFFFF),
        surfaceContainer = Color(0xFFFFFFFF),
        surfaceContainerHigh = Color(0xFFFFFFFF),
        surfaceContainerHighest = Color(0xFFFFFFFF),
    )

    override val darkScheme = darkColorScheme(
        primary = Color(0xFFFFFFFF),
        onPrimary = Color(0xFF000000),
        primaryContainer = Color(0xFFFFFFFF),
        onPrimaryContainer = Color(0xFF000000),
        secondary = Color(0xFFFFFFFF),
        onSecondary = Color(0xFF000000),
        secondaryContainer = Color(0xFF808080),
        onSecondaryContainer = Color(0xFFFFFFFF),
        tertiary = Color(0xFFFFFFFF),
        onTertiary = Color(0xFF000000),
        tertiaryContainer = Color(0xFFFFFFFF),
        onTertiaryContainer = Color(0xFF000000),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        background = Color(0xFF000000),
        onBackground = Color(0xFFFFFFFF),
        surface = Color(0xFF000000),
        onSurface = Color(0xFFFFFFFF),
        surfaceVariant = Color(0xFF444846),
        onSurfaceVariant = Color(0xFFC4C7C5),
        outline = Color(0xFF8E918F),
        outlineVariant = Color(0xFF444846),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFFE5E2E1),
        inverseOnSurface = Color(0xFF313030),
        inversePrimary = Color(0xFF5D5F5F),
        primaryFixed = Color(0xFFE2E2E2),
        onPrimaryFixed = Color(0xFF1A1C1C),
        primaryFixedDim = Color(0xFFC6C6C7),
        onPrimaryFixedVariant = Color(0xFF454747),
        secondaryFixed = Color(0xFFE2E2E2),
        onSecondaryFixed = Color(0xFF1B1B1B),
        secondaryFixedDim = Color(0xFFC6C6C6),
        onSecondaryFixedVariant = Color(0xFF474747),
        tertiaryFixed = Color(0xFFE2E2E2),
        onTertiaryFixed = Color(0xFF1B1B1B),
        tertiaryFixedDim = Color(0xFFC6C6C6),
        onTertiaryFixedVariant = Color(0xFF474747),
        surfaceDim = Color(0xFF141313),
        surfaceBright = Color(0xFF3A3939),
        surfaceContainerLowest = Color(0xFF0E0E0E),
        surfaceContainerLow = Color(0xFF1C1B1B),
        surfaceContainer = Color(0xFF000000),
        surfaceContainerHigh = Color(0xFF2A2A2A),
        surfaceContainerHighest = Color(0xFF353434),
    )
}