package io.legado.app.ui.theme.colorScheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import io.legado.app.ui.theme.BaseColorScheme

internal object KoharuColorScheme : BaseColorScheme() {

    override val lightScheme = lightColorScheme(
        primary = Color(0xFF8F4A4D),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFFDADA),
        onPrimaryContainer = Color(0xFF3B080E),
        secondary = Color(0xFF765657),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFFFDADA),
        onSecondaryContainer = Color(0xFF2C1516),
        tertiary = Color(0xFF755A2F),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFFFDDB0),
        onTertiaryContainer = Color(0xFF291800),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF93000A),
        background = Color(0xFFFFF8F7),
        onBackground = Color(0xFF221919),
        surface = Color(0xFFFFF8F7),
        onSurface = Color(0xFF221919),
        surfaceVariant = Color(0xFFF4DDDD),
        onSurfaceVariant = Color(0xFF524343),
        outline = Color(0xFF857373),
        outlineVariant = Color(0xFFD7C1C1),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFF382E2E),
        inverseOnSurface = Color(0xFFFFEDEC),
        inversePrimary = Color(0xFFFFB3B4),
        primaryFixed = Color(0xFFFFDADA),
        onPrimaryFixed = Color(0xFF3B080E),
        primaryFixedDim = Color(0xFFFFB3B4),
        onPrimaryFixedVariant = Color(0xFF733337),
        secondaryFixed = Color(0xFFFFDADA),
        onSecondaryFixed = Color(0xFF2C1516),
        secondaryFixedDim = Color(0xFFE6BDBD),
        onSecondaryFixedVariant = Color(0xFF5D3F40),
        tertiaryFixed = Color(0xFFFFDDB0),
        onTertiaryFixed = Color(0xFF291800),
        tertiaryFixedDim = Color(0xFFE6C18D),
        onTertiaryFixedVariant = Color(0xFF5B421A),
        surfaceDim = Color(0xFFE8D6D6),
        surfaceBright = Color(0xFFFFF8F7),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFFFF0F0),
        surfaceContainer = Color(0xFFFCEAE9),
        surfaceContainerHigh = Color(0xFFF6E4E4),
        surfaceContainerHighest = Color(0xFFF0DEDE),
    )

    override val darkScheme = darkColorScheme(
        primary = Color(0xFFFFB3B4),
        onPrimary = Color(0xFF561D22),
        primaryContainer = Color(0xFF733337),
        onPrimaryContainer = Color(0xFFFFDADA),
        secondary = Color(0xFFE6BDBD),
        onSecondary = Color(0xFF44292A),
        secondaryContainer = Color(0xFF5D3F40),
        onSecondaryContainer = Color(0xFFFFDADA),
        tertiary = Color(0xFFE6C18D),
        onTertiary = Color(0xFF422C05),
        tertiaryContainer = Color(0xFF5B421A),
        onTertiaryContainer = Color(0xFFFFDDB0),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        background = Color(0xFF1A1111),
        onBackground = Color(0xFFF0DEDE),
        surface = Color(0xFF1A1111),
        onSurface = Color(0xFFF0DEDE),
        surfaceVariant = Color(0xFF524343),
        onSurfaceVariant = Color(0xFFD7C1C1),
        outline = Color(0xFF9F8C8C),
        outlineVariant = Color(0xFF524343),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFFF0DEDE),
        inverseOnSurface = Color(0xFF382E2E),
        inversePrimary = Color(0xFF8F4A4D),
        primaryFixed = Color(0xFFFFDADA),
        onPrimaryFixed = Color(0xFF3B080E),
        primaryFixedDim = Color(0xFFFFB3B4),
        onPrimaryFixedVariant = Color(0xFF733337),
        secondaryFixed = Color(0xFFFFDADA),
        onSecondaryFixed = Color(0xFF2C1516),
        secondaryFixedDim = Color(0xFFE6BDBD),
        onSecondaryFixedVariant = Color(0xFF5D3F40),
        tertiaryFixed = Color(0xFFFFDDB0),
        onTertiaryFixed = Color(0xFF291800),
        tertiaryFixedDim = Color(0xFFE6C18D),
        onTertiaryFixedVariant = Color(0xFF5B421A),
        surfaceDim = Color(0xFF1A1111),
        surfaceBright = Color(0xFF413737),
        surfaceContainerLowest = Color(0xFF140C0C),
        surfaceContainerLow = Color(0xFF221919),
        surfaceContainer = Color(0xFF271D1D),
        surfaceContainerHigh = Color(0xFF322828),
        surfaceContainerHighest = Color(0xFF3D3232),
    )
}