package io.legado.app.ui.theme.colorScheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import io.legado.app.ui.theme.BaseColorScheme

internal object PhoebeColorScheme : BaseColorScheme() {

    override val lightScheme = lightColorScheme(
        primary = Color(0xFF6B5E10),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFF6E388),
        onPrimaryContainer = Color(0xFF524700),
        secondary = Color(0xFF475D92),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFD9E2FF),
        onSecondaryContainer = Color(0xFF2F4578),
        tertiary = Color(0xFF01677D),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFB3EBFF),
        onTertiaryContainer = Color(0xFF004E5F),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF93000A),
        background = Color(0xFFFFF9EC),
        onBackground = Color(0xFF1E1C13),
        surface = Color(0xFFFFF9EC),
        onSurface = Color(0xFF1E1C13),
        surfaceVariant = Color(0xFFE9E2D0),
        onSurfaceVariant = Color(0xFF4A4739),
        outline = Color(0xFF7C7768),
        outlineVariant = Color(0xFFCCC6B4),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFF333027),
        inverseOnSurface = Color(0xFFF6F0E2),
        inversePrimary = Color(0xFFD9C76F),
        primaryFixed = Color(0xFFF6E388),
        onPrimaryFixed = Color(0xFF211B00),
        primaryFixedDim = Color(0xFFD9C76F),
        onPrimaryFixedVariant = Color(0xFF524700),
        secondaryFixed = Color(0xFFD9E2FF),
        onSecondaryFixed = Color(0xFF001946),
        secondaryFixedDim = Color(0xFFB1C5FF),
        onSecondaryFixedVariant = Color(0xFF2F4578),
        tertiaryFixed = Color(0xFFB3EBFF),
        onTertiaryFixed = Color(0xFF001F27),
        tertiaryFixedDim = Color(0xFF86D1EA),
        onTertiaryFixedVariant = Color(0xFF004E5F),
        surfaceDim = Color(0xFFDFDACC),
        surfaceBright = Color(0xFFFFF9EC),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFF9F3E5),
        surfaceContainer = Color(0xFFF4EDDF),
        surfaceContainerHigh = Color(0xFFEEE8DA),
        surfaceContainerHighest = Color(0xFFE8E2D4),
    )

    override val darkScheme = darkColorScheme(
        primary = Color(0xFFD9C76F),
        onPrimary = Color(0xFF383000),
        primaryContainer = Color(0xFF524700),
        onPrimaryContainer = Color(0xFFF6E388),
        secondary = Color(0xFFB1C5FF),
        onSecondary = Color(0xFF162E60),
        secondaryContainer = Color(0xFF2F4578),
        onSecondaryContainer = Color(0xFFD9E2FF),
        tertiary = Color(0xFF86D1EA),
        onTertiary = Color(0xFF003642),
        tertiaryContainer = Color(0xFF004E5F),
        onTertiaryContainer = Color(0xFFB3EBFF),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        background = Color(0xFF15130C),
        onBackground = Color(0xFFE8E2D4),
        surface = Color(0xFF15130C),
        onSurface = Color(0xFFE8E2D4),
        surfaceVariant = Color(0xFF4A4739),
        onSurfaceVariant = Color(0xFFCCC6B4),
        outline = Color(0xFF969180),
        outlineVariant = Color(0xFF4A4739),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFFE8E2D4),
        inverseOnSurface = Color(0xFF333027),
        inversePrimary = Color(0xFF6B5E10),
        primaryFixed = Color(0xFFF6E388),
        onPrimaryFixed = Color(0xFF211B00),
        primaryFixedDim = Color(0xFFD9C76F),
        onPrimaryFixedVariant = Color(0xFF524700),
        secondaryFixed = Color(0xFFD9E2FF),
        onSecondaryFixed = Color(0xFF001946),
        secondaryFixedDim = Color(0xFFB1C5FF),
        onSecondaryFixedVariant = Color(0xFF2F4578),
        tertiaryFixed = Color(0xFFB3EBFF),
        onTertiaryFixed = Color(0xFF001F27),
        tertiaryFixedDim = Color(0xFF86D1EA),
        onTertiaryFixedVariant = Color(0xFF004E5F),
        surfaceDim = Color(0xFF15130C),
        surfaceBright = Color(0xFF3C3930),
        surfaceContainerLowest = Color(0xFF100E07),
        surfaceContainerLow = Color(0xFF1E1C13),
        surfaceContainer = Color(0xFF222017),
        surfaceContainerHigh = Color(0xFF2C2A21),
        surfaceContainerHighest = Color(0xFF37352B),
    )
}