package io.legado.app.ui.theme.colorScheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import io.legado.app.ui.theme.BaseColorScheme

internal object SoraColorScheme : BaseColorScheme() {

    override val lightScheme = lightColorScheme(
        primary = Color(0xFF3B608F),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFD4E3FF),
        onPrimaryContainer = Color(0xFF214876),
        secondary = Color(0xFF545F71),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFD8E3F8),
        onSecondaryContainer = Color(0xFF3D4758),
        tertiary = Color(0xFF6D5677),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFF6D9FF),
        onTertiaryContainer = Color(0xFF543F5E),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF93000A),
        background = Color(0xFFF8F9FF),
        onBackground = Color(0xFF191C20),
        surface = Color(0xFFF8F9FF),
        onSurface = Color(0xFF191C20),
        surfaceVariant = Color(0xFFDFE2EB),
        onSurfaceVariant = Color(0xFF43474E),
        outline = Color(0xFF73777F),
        outlineVariant = Color(0xFFC3C6CF),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFF2E3035),
        inverseOnSurface = Color(0xFFF0F0F7),
        inversePrimary = Color(0xFFA5C9FE),
        primaryFixed = Color(0xFFD4E3FF),
        onPrimaryFixed = Color(0xFF001C38),
        primaryFixedDim = Color(0xFFA5C9FE),
        onPrimaryFixedVariant = Color(0xFF214876),
        secondaryFixed = Color(0xFFD8E3F8),
        onSecondaryFixed = Color(0xFF111C2B),
        secondaryFixedDim = Color(0xFFBCC7DC),
        onSecondaryFixedVariant = Color(0xFF3D4758),
        tertiaryFixed = Color(0xFFF6D9FF),
        onTertiaryFixed = Color(0xFF271731),
        tertiaryFixedDim = Color(0xFFD9BDE3),
        onTertiaryFixedVariant = Color(0xFF543F5E),
        surfaceDim = Color(0xFFD9DAE0),
        surfaceBright = Color(0xFFF8F9FF),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFF2F3FA),
        surfaceContainer = Color(0xFFEDEDF4),
        surfaceContainerHigh = Color(0xFFE7E8EE),
        surfaceContainerHighest = Color(0xFFE1E2E9),
    )

    override val darkScheme = darkColorScheme(
        primary = Color(0xFFA5C9FE),
        onPrimary = Color(0xFF00315D),
        primaryContainer = Color(0xFF214876),
        onPrimaryContainer = Color(0xFFD4E3FF),
        secondary = Color(0xFFBCC7DC),
        onSecondary = Color(0xFF263141),
        secondaryContainer = Color(0xFF3D4758),
        onSecondaryContainer = Color(0xFFD8E3F8),
        tertiary = Color(0xFFD9BDE3),
        onTertiary = Color(0xFF3D2946),
        tertiaryContainer = Color(0xFF543F5E),
        onTertiaryContainer = Color(0xFFF6D9FF),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        background = Color(0xFF111318),
        onBackground = Color(0xFFE1E2E9),
        surface = Color(0xFF111318),
        onSurface = Color(0xFFE1E2E9),
        surfaceVariant = Color(0xFF43474E),
        onSurfaceVariant = Color(0xFFC3C6CF),
        outline = Color(0xFF8D9199),
        outlineVariant = Color(0xFF43474E),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFFE1E2E9),
        inverseOnSurface = Color(0xFF2E3035),
        inversePrimary = Color(0xFF3B608F),
        primaryFixed = Color(0xFFD4E3FF),
        onPrimaryFixed = Color(0xFF001C38),
        primaryFixedDim = Color(0xFFA5C9FE),
        onPrimaryFixedVariant = Color(0xFF214876),
        secondaryFixed = Color(0xFFD8E3F8),
        onSecondaryFixed = Color(0xFF111C2B),
        secondaryFixedDim = Color(0xFFBCC7DC),
        onSecondaryFixedVariant = Color(0xFF3D4758),
        tertiaryFixed = Color(0xFFF6D9FF),
        onTertiaryFixed = Color(0xFF271731),
        tertiaryFixedDim = Color(0xFFD9BDE3),
        onTertiaryFixedVariant = Color(0xFF543F5E),
        surfaceDim = Color(0xFF111318),
        surfaceBright = Color(0xFF37393E),
        surfaceContainerLowest = Color(0xFF0C0E13),
        surfaceContainerLow = Color(0xFF191C20),
        surfaceContainer = Color(0xFF1D2024),
        surfaceContainerHigh = Color(0xFF282A2F),
        surfaceContainerHighest = Color(0xFF32353A),
    )
}