package io.legado.app.ui.theme.colorScheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import io.legado.app.ui.theme.BaseColorScheme

internal object TransparentColorScheme : BaseColorScheme() {

    override val lightScheme = lightColorScheme(
        primary = Color(0xFF000000),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xB0FFFFFF),
        onPrimaryContainer = Color(0xFF000000),
        secondary = Color(0xFF000000),
        onSecondary = Color(0xB0FFFFFF),
        secondaryContainer = Color(0xB0FFFFFF),
        onSecondaryContainer = Color(0xFF000000),
        tertiary = Color(0xFF000000),
        onTertiary = Color(0xFF000000),
        tertiaryContainer = Color(0xB0FFFFFF),
        onTertiaryContainer = Color(0xFF000000),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF93000A),
        background = Color(0x00FFFFFF),
        onBackground = Color(0xFF1E1C13),
        surface = Color(0x00FFFFFF),
        onSurface = Color(0xFF1E1C13),
        surfaceVariant = Color(0x1A000000),
        onSurfaceVariant = Color(0x80000000),
        outline = Color(0xFF7C7768),
        outlineVariant = Color(0xFFCCC6B4),
        scrim = Color(0x33000000),
        inverseSurface = Color(0xFF333027),
        inverseOnSurface = Color(0xFFF6F0E2),
        inversePrimary = Color(0xA0FFFFFF),
        primaryFixed = Color(0xA0FFFFFF),
        onPrimaryFixed = Color(0xFF211B00),
        primaryFixedDim = Color(0xB0FFFFFF),
        onPrimaryFixedVariant = Color(0xB0FFFFFF),
        secondaryFixed = Color(0xB0FFFFFF),
        onSecondaryFixed = Color(0xFF000000),
        secondaryFixedDim = Color(0xB0FFFFFF),
        onSecondaryFixedVariant = Color(0xB0FFFFFF),
        tertiaryFixed = Color(0xB0FFFFFF),
        onTertiaryFixed = Color(0xFF000000),
        tertiaryFixedDim = Color(0xB0FFFFFF),
        onTertiaryFixedVariant = Color(0xB0FFFFFF),
        surfaceDim = Color(0x1AFFFFFF),
        surfaceBright = Color(0x33FFFFFF),
        surfaceContainerLowest = Color(0x0DFFFFFF),
        surfaceContainerLow = Color(0x8FFFFFFF),
        surfaceContainer = Color(0x33FFFFFF),
        surfaceContainerHigh = Color(0x4DFFFFFF),
        surfaceContainerHighest = Color(0x66FFFFFF),
    )

    override val darkScheme = darkColorScheme(
        primary = Color(0xA0FFFFFF),
        onPrimary = Color(0xFF000000),
        primaryContainer = Color(0x80FFFFFF),
        onPrimaryContainer = Color(0xFF000000),
        secondary = Color(0x80FFFFFF),
        onSecondary = Color(0xFF000000),
        secondaryContainer = Color(0xA0FFFFFF),
        onSecondaryContainer = Color(0xFF000000),
        tertiary = Color(0x80FFFFFF),
        onTertiary = Color(0xFF000000),
        tertiaryContainer = Color(0x40FFFFFF),
        onTertiaryContainer = Color(0xFF000000),
        error = Color(0xFFCF6679),
        onError = Color(0xFF000000),
        errorContainer = Color(0xFF8B0000),
        onErrorContainer = Color(0xFFFFFFFF),
        background = Color(0x00000000),
        onBackground = Color(0xFFEDE6FF),
        surface = Color(0x00FFFFFF),
        onSurface = Color(0xFFEDE6FF),
        surfaceVariant = Color(0x40FFFFFF),
        onSurfaceVariant = Color(0xB3FFFFFF),
        outline = Color(0x8AFFFFFF),
        outlineVariant = Color(0x33FFFFFF),
        scrim = Color(0x66000000),
        inverseSurface = Color(0xFFFFF9EC),
        inverseOnSurface = Color(0xFF1E1C13),
        inversePrimary = Color(0xA0FFFFFF),
        primaryFixed = Color(0xA0FFFFFF),
        onPrimaryFixed = Color(0xFF000000),
        primaryFixedDim = Color(0xA0FFFFFF),
        onPrimaryFixedVariant = Color(0xA0FFFFFF),
        secondaryFixed = Color(0xA0FFFFFF),
        onSecondaryFixed = Color(0xFF000000),
        secondaryFixedDim = Color(0xA0FFFFFF),
        onSecondaryFixedVariant = Color(0xA0FFFFFF),
        tertiaryFixed = Color(0xA0FFFFFF),
        onTertiaryFixed = Color(0xFF000000),
        tertiaryFixedDim = Color(0xA0FFFFFF),
        onTertiaryFixedVariant = Color(0xA0FFFFFF),
        surfaceDim = Color(0x1AFFFFFF),
        surfaceBright = Color(0x33FFFFFF),
        surfaceContainerLowest = Color(0x0DFFFFFF),
        surfaceContainerLow = Color(0x8F000000),
        surfaceContainer = Color(0x33FFFFFF),
        surfaceContainerHigh = Color(0x4DFFFFFF),
        surfaceContainerHighest = Color(0x66FFFFFF),
    )
}