package io.legado.app.ui.theme.colorScheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import io.legado.app.ui.theme.BaseColorScheme

internal object WHColorScheme: BaseColorScheme() {
    override val lightScheme = lightColorScheme(
        primary = Color(0xFF5C5C5C),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFF747474),
        onPrimaryContainer = Color(0xFFFEFCFC),
        secondary = Color(0xFF5F5E5E),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFE2DFDE),
        onSecondaryContainer = Color(0xFF636262),
        tertiary = Color(0xFF5E5B5D),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFF777375),
        onTertiaryContainer = Color(0xFFFFFBFF),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF93000A),
        background = Color(0xFFFAFAFA),
        onBackground = Color(0xFF1C1B1B),
        surface = Color(0xFFF8F8F8),
        onSurface = Color(0xFF1C1B1B),
        surfaceVariant = Color(0xFFE0E3E3),
        onSurfaceVariant = Color(0xFF444748),
        outline = Color(0xFF747878),
        outlineVariant = Color(0xFFC4C7C7),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFF313030),
        inverseOnSurface = Color(0xFFF4F0EF),
        inversePrimary = Color(0xFFC7C6C6),
        primaryFixed = Color(0xFFE3E2E2),
        onPrimaryFixed = Color(0xFF1A1C1C),
        primaryFixedDim = Color(0xFFC7C6C6),
        onPrimaryFixedVariant = Color(0xFF454747),
        secondaryFixed = Color(0xFFE2DFDE),
        onSecondaryFixed = Color(0xFF1C1B1B),
        secondaryFixedDim = Color(0xFFC6C6C6),
        onSecondaryFixedVariant = Color(0xFF474747),
        tertiaryFixed = Color(0xFFE5E2E4),
        onTertiaryFixed = Color(0xFF1C1B1D),
        tertiaryFixedDim = Color(0xFFC9C5C7),
        onTertiaryFixedVariant = Color(0xFF494648),
        surfaceDim = Color(0xFFDDD9D8),
        surfaceBright = Color(0xFFF8F8F8),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFF7F3F2),
        surfaceContainer = Color(0xFFF1EDEC),
        surfaceContainerHigh = Color(0xFFEBE7E7),
        surfaceContainerHighest = Color(0xFFE5E2E1),
    )

    override val darkScheme = darkColorScheme(
        primary = Color(0xFFC7C6C6),
        onPrimary = Color(0xFF303031),
        primaryContainer = Color(0xFF919090),
        onPrimaryContainer = Color(0xFF050606),
        secondary = Color(0xFFC8C6C5),
        onSecondary = Color(0xFF303030),
        secondaryContainer = Color(0xFF474746),
        onSecondaryContainer = Color(0xFFB7B5B4),
        tertiary = Color(0xFFCBC5C7),
        onTertiary = Color(0xFF323031),
        tertiaryContainer = Color(0xFF948F91),
        onTertiaryContainer = Color(0xFF060506),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        background = Color(0xFF141313),
        onBackground = Color(0xFFE5E2E1),
        surface = Color(0xFF141313),
        onSurface = Color(0xFFE5E2E1),
        surfaceVariant = Color(0xFF444748),
        onSurfaceVariant = Color(0xFFC4C7C7),
        outline = Color(0xFF8E918F),
        outlineVariant = Color(0xFF444748),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFFE5E2E1),
        inverseOnSurface = Color(0xFF313030),
        inversePrimary = Color(0xFF5E5E5E),
        primaryFixed = Color(0xFFE3E2E2),
        onPrimaryFixed = Color(0xFF1A1C1C),
        primaryFixedDim = Color(0xFFC7C6C6),
        onPrimaryFixedVariant = Color(0xFF454747),
        secondaryFixed = Color(0xFFE2DFDE),
        onSecondaryFixed = Color(0xFF1C1B1B),
        secondaryFixedDim = Color(0xFFC6C6C6),
        onSecondaryFixedVariant = Color(0xFF474747),
        tertiaryFixed = Color(0xFFE5E2E4),
        onTertiaryFixed = Color(0xFF1C1B1D),
        tertiaryFixedDim = Color(0xFFC9C5C7),
        onTertiaryFixedVariant = Color(0xFF494648),
        surfaceDim = Color(0xFF141313),
        surfaceBright = Color(0xFF3A3939),
        surfaceContainerLowest = Color(0xFF0E0E0E),
        surfaceContainerLow = Color(0xFF1C1B1B),
        surfaceContainer = Color(0xFF201F1F),
        surfaceContainerHigh = Color(0xFF2A2A2A),
        surfaceContainerHighest = Color(0xFF353434),
    )
}