package io.legado.app.ui.theme.colorScheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import io.legado.app.ui.theme.BaseColorScheme

internal object YuukaColorScheme : BaseColorScheme() {

    override val lightScheme = lightColorScheme(
        primary = Color(0xFF565992),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFE0E0FF),
        onPrimaryContainer = Color(0xFF3E4278),
        secondary = Color(0xFF5C5D72),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFE1E0F9),
        onSecondaryContainer = Color(0xFF444559),
        tertiary = Color(0xFF78536B),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFFFD8EE),
        onTertiaryContainer = Color(0xFF5E3C52),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF93000A),
        background = Color(0xFFFBF8FF),
        onBackground = Color(0xFF1B1B21),
        surface = Color(0xFFFBF8FF),
        onSurface = Color(0xFF1B1B21),
        surfaceVariant = Color(0xFFE4E1EC),
        onSurfaceVariant = Color(0xFF46464F),
        outline = Color(0xFF777680),
        outlineVariant = Color(0xFFC7C5D0),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFF303036),
        inverseOnSurface = Color(0xFFF2EFF7),
        inversePrimary = Color(0xFFBFC2FF),
        primaryFixed = Color(0xFFE0E0FF),
        onPrimaryFixed = Color(0xFF11144B),
        primaryFixedDim = Color(0xFFBFC2FF),
        onPrimaryFixedVariant = Color(0xFF3E4278),
        secondaryFixed = Color(0xFFE1E0F9),
        onSecondaryFixed = Color(0xFF191A2C),
        secondaryFixedDim = Color(0xFFC5C4DD),
        onSecondaryFixedVariant = Color(0xFF444559),
        tertiaryFixed = Color(0xFFFFD8EE),
        onTertiaryFixed = Color(0xFF2E1126),
        tertiaryFixedDim = Color(0xFFE8B9D5),
        onTertiaryFixedVariant = Color(0xFF5E3C52),
        surfaceDim = Color(0xFFDBD9E0),
        surfaceBright = Color(0xFFFBF8FF),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFF5F2FA),
        surfaceContainer = Color(0xFFF0ECF4),
        surfaceContainerHigh = Color(0xFFEAE7EF),
        surfaceContainerHighest = Color(0xFFE4E1E9),
    )

    override val darkScheme = darkColorScheme(
        primary = Color(0xFFBFC2FF),
        onPrimary = Color(0xFF272B60),
        primaryContainer = Color(0xFF3E4278),
        onPrimaryContainer = Color(0xFFE0E0FF),
        secondary = Color(0xFFC5C4DD),
        onSecondary = Color(0xFF2E2F42),
        secondaryContainer = Color(0xFF444559),
        onSecondaryContainer = Color(0xFFE1E0F9),
        tertiary = Color(0xFFE8B9D5),
        onTertiary = Color(0xFF46263B),
        tertiaryContainer = Color(0xFF5E3C52),
        onTertiaryContainer = Color(0xFFFFD8EE),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        background = Color(0xFF131318),
        onBackground = Color(0xFFE4E1E9),
        surface = Color(0xFF131318),
        onSurface = Color(0xFFE4E1E9),
        surfaceVariant = Color(0xFF46464F),
        onSurfaceVariant = Color(0xFFC7C5D0),
        outline = Color(0xFF918F9A),
        outlineVariant = Color(0xFF46464F),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFFE4E1E9),
        inverseOnSurface = Color(0xFF303036),
        inversePrimary = Color(0xFF565992),
        primaryFixed = Color(0xFFE0E0FF),
        onPrimaryFixed = Color(0xFF11144B),
        primaryFixedDim = Color(0xFFBFC2FF),
        onPrimaryFixedVariant = Color(0xFF3E4278),
        secondaryFixed = Color(0xFFE1E0F9),
        onSecondaryFixed = Color(0xFF191A2C),
        secondaryFixedDim = Color(0xFFC5C4DD),
        onSecondaryFixedVariant = Color(0xFF444559),
        tertiaryFixed = Color(0xFFFFD8EE),
        onTertiaryFixed = Color(0xFF2E1126),
        tertiaryFixedDim = Color(0xFFE8B9D5),
        onTertiaryFixedVariant = Color(0xFF5E3C52),
        surfaceDim = Color(0xFF131318),
        surfaceBright = Color(0xFF39393F),
        surfaceContainerLowest = Color(0xFF0E0E13),
        surfaceContainerLow = Color(0xFF1B1B21),
        surfaceContainer = Color(0xFF1F1F25),
        surfaceContainerHigh = Color(0xFF2A292F),
        surfaceContainerHighest = Color(0xFF34343A),
    )
}