name: Backup Repositories

on:
  schedule:
    - cron: '0 */2 * * *'  
  workflow_dispatch:
  
jobs:
  backup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Backup Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          
- name: Clone Luoyacheng_legado
  run: |
    git clone --depth=1 --branch master https://github.com/Luoyacheng/legado Luoyacheng_legado
    if [ -d "legado(Luoyacheng)" ]; then
    rm -rf "legado(Luoyacheng)"
    fi
    mkdir -p "legado(Luoyacheng)"
    mv Luoyacheng_legado/* "legado(Luoyacheng)/"
    rm -rf Luoyacheng_legado
  
          
      - name: Update timestamp
        run: echo "Backup run at $(date)" > backup-timestamp.txt
        
      - name: Commit and Push Changes
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff-index --quiet HEAD; then
            echo "No changes detected, adding timestamp file."
            echo "Backup run at $(date)" > backup-timestamp.txt
            git add backup-timestamp.txt
            git commit -m "$(date +'%Y-%m-%d %H:%M:%S')"
          else
            git commit -m "Automated backup $(date +'%Y-%m-%d %H:%M:%S')"
          fi
          git remote set-url origin https://x-access-token:${PAT}@github.com/smjcxf/yuedu.git
          git push origin main
